name: Auto approve

on:
  pull_request:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
  automerge:
    needs: auto-approve
    runs-on: ubuntu-latest
    steps:
    - uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        target: patch
        github-token: ${{ secrets.GITHUB_TOKEN }}
             